defaults:
  - model_checkpoint
  - model_summary
  - rich_progress_bar
  - learning_rate_monitor
  - early_stopping
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/mean_dice"
  mode: "max"
  save_last: False
  auto_insert_metric_name: False

early_stopping:
  _target_: lightning.pytorch.callbacks.EarlyStopping
  monitor: val/mean_dice
  patience: 15
  mode: "max"
  verbose: True

model_summary:
  max_depth: -1
