defaults:
  - net: unet
  - optimizer: sgd
  - scheduler: polylr
  - loss: dice_ce

_target_: patchless_nnunet.models.patchless_nnunet_module.nnUNetPatchlessLitModule

optimizer_monitor: val/mean_dice

tta: True
save_predictions: False
save_npz: False

name: patchless_nnunet

common_spacing: [0.37, 0.37, 1]

net:
  in_channels: 1
  num_classes: 3
  patch_size: [352, 288, 20]
  kernels: [[3, 3, 1], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]
  strides: [[1, 1, 1], [2, 2, 1], [2, 2, 2], [2, 2, 2], [2, 2, 1], [2, 2, 1]]

loss:
  soft_dice_kwargs: {"batch_dice": False, "smooth": 1e-05, "do_bg": False}
