# @package _global_

defaults:
  - model: patchless_nnunet
  - trainer: patchless_nnunet
  - paths: default
  - extras: default
  - hydra: patchless_nnunet
  - _self_

task_name: "predict"

tags: ["predict"]

# input folder containing data for inference
input_folder: 'F:\icardio\data\test_slice.nii'

# output folder to save predictions
output_folder: 'F:\icardio\output'

# passing checkpoint path is necessary for prediction
ckpt_path: 'F:\icardio\checkpoint_file\patchless_best_window_len_4_1.ckpt'

# whether to use test time augmentation
tta: False

# whether to overwrite existing predictions in the output folder
overwrite_existing: True

pin_memory: True

num_workers: 8

hydra:
  output_subdir: null
  run:
    dir: ${output_folder}

paths:
  output_dir: ${output_folder}

model:
  save_predictions: True
  tta: ${tta}
