# https://neptune.ai

neptune:
  _target_: lightning.pytorch.loggers.neptune.NeptuneLogger
  api_key: ${oc.env:NEPTUNE_API_TOKEN} # api key is loaded from environment variable
  project: username/patchless_nnunet
  # name: ""
  log_model_checkpoints: True
  prefix: ""
